PianoDiProgetto.pdf: ../../Comandi.sty ../../Stile.sty PianoDiProgetto.tex
	@cd /home/mainuser/bash_script && sh compila_doc.sh /home/mainuser/DocSWE/Esterni/PianoDiProgetto PianoDiProgetto
	@cp PianoDiProgetto.pdf /home/mainuser/DocSWE/pdfdoc/Esterni/PianoDiProgetto/
	@rm *.aux *.lof *.log *.lot *.out *.toc