SpecificaTecnica.pdf: ../../Comandi.sty ../../Stile.sty *.tex
	@cd /home/mainuser/bash_script && sh compila_doc.sh /home/mainuser/DocSWE/Esterni/SpecificaTecnica SpecificaTecnica
	@cp SpecificaTecnica.pdf /home/mainuser/DocSWE/pdfdoc/Esterni/SpecificaTecnica/