PianoDiQualifica.pdf: ../../Comandi.sty ../../Stile.sty PianoDiQualifica.tex
	@cd /home/mainuser/bash_script && sh compila_doc.sh /home/mainuser/DocSWE/Esterni/PianoDiQualifica PianoDiQualifica
	@cp PianoDiQualifica.pdf /home/mainuser/DocSWE/pdfdoc/Esterni/PianoDiQualifica/
	@rm *.aux *.lof *.log *.lot *.out *.toc