NormeDiProgetto.pdf: ../../Comandi.sty ../../Stile.sty NormeDiProgetto.tex
	@cd /home/mainuser/bash_script && sh compila_doc.sh /home/mainuser/DocSWE/Interni/NormeDiProgetto NormeDiProgetto
	@cp NormeDiProgetto.pdf /home/mainuser/DocSWE/pdfdoc/Interni/NormeDiProgetto/