Glossario.pdf: ../../Comandi.sty ../../Stile.sty DefinizioneDiProdotto.tex diary.tex
	@cd /home/mainuser/bash_script && sh compila_doc.sh /home/mainuser/DocSWE/Esterni/DefinizioneDiProdotto DefinizioneDiProdotto
	@cp DefinizioneDiProdotto.pdf /home/mainuser/DocSWE/pdfdoc/Esterni/DefinizioneDiProdotto/
