AnalisiDeiRequisiti.pdf: ../../Comandi.sty ../../Stile.sty AnalisiDeiRequisiti.tex auto_casiuso.tex auto_req_funz.tex auto_req_pres.tex auto_req_qual.tex auto_req_vinc.tex auto_req_summary.tex auto_track_fr.tex auto_track_rf.tex
	pdflatex AnalisiDeiRequisiti.tex && pdflatex AnalisiDeiRequisiti.tex
