AnalisiDeiRequisiti.pdf: ../../Comandi.sty ../../Stile.sty *.tex Img/*.pdf
	@cd /home/mainuser/bash_script && sh compila_doc.sh /home/mainuser/DocSWE/Esterni/AnalisiDeiRequisiti AnalisiDeiRequisiti
	@cp AnalisiDeiRequisiti.pdf /home/mainuser/DocSWE/pdfdoc/Esterni/AnalisiDeiRequisiti/