AnalisiDeiRequisiti.pdf: ../../Comandi.sty ../../Stile.sty AnalisiDeiRequisiti.tex auto_casiuso.tex auto_req_funz.tex auto_req_pres.tex auto_req_qual.tex auto_req_vinc.tex auto_req_summary.tex auto_track_fr.tex auto_track_rf.tex
	@cd /home/mainuser/bash_script && sh compila_doc.sh /home/mainuser/DocSWE/Esterni/AnalisiDeiRequisiti AnalisiDeiRequisiti
	@cp AnalisiDeiRequisiti.pdf /home/mainuser/DocSWE/pdfdoc/Esterni/AnalisiDeiRequisiti/
	@rm *.aux *.lof *.log *.lot *.out *.toc