Glossario.pdf: ../../Comandi.sty ../../Stile.sty Glossario.tex voci.tex
	@cd /home/mainuser/bash_script && sh compila_doc.sh /home/mainuser/DocSWE/Esterni/Glossario Glossario
	@cp Glossario.pdf /home/mainuser/DocSWE/pdfdoc/Esterni/Glossario/
	@rm *.aux *.lof *.log *.lot *.out *.toc
