Error = Type  H <return>  for immediate help.

Glossario.pdf: ../../Comandi.sty ../../Stile.sty Glossario.tex voci.tex
	@cd /home/mainuser/bash_script && sh compila_doc.sh /home/mainuser/DocSWE/Esterni/Glossario Glossario